Shokhista: Homework 4 completed
eugene-okulik/shokhista pull request #3
Opened 2024-08-07 05:43 UTC by ShakhistaKh

2024-08-07 08:45 UTC, eugene-okulik requested changes
Всё ок, но нужно поправить всё, на что ругается линт  
И еще, ты забыла, что создавать ветку нужно не из ветки предыдущего задания, а из ветки main, которую, перед созданием из нее ветки, нужно обновить (сделать git pull). Вот здесь есть памятка о правильной последовательности действий: https://github.com/eugene-okulik/shokhista/wiki  
С веткой ничего сейчас исправлять не надо - просто имей в виду при выполнении следующего задания.

2024-08-07 08:45 UTC, eugene-okulik commented on homework/shokhista_khashimova/homework_4/task_1 by step.py
> +# Количество элементов в кортеже должно быть не меньше пяти.
Здесь в конце третьей строки есть лишний пробел и линт на него ругается

2024-08-07 08:45 UTC, eugene-okulik commented on homework/shokhista_khashimova/homework_4/task_2 by step.py
> +# Создайте словарь (и сохраните его в переменную my_dict) с такими ключами:
Здесь после первой строки тоже есть пробел, на который ругается линт

2024-08-07 08:45 UTC, eugene-okulik commented on homework/shokhista_khashimova/homework_4/task_2 by step.py
> +my_dict = {'tuple': (1, "q", "A", "z", "word"), 'list': ["first", "second", "third", "cat", "dog"],
И здесь после 12-й строки тоже есть пробел, на который ругается линт

2024-08-07 08:45 UTC, eugene-okulik commented on homework/shokhista_khashimova/homework_4/task_2 by step.py
> +#Для того, что хранится под ключом ‘tuple’ выведите на экран последний элемент
Везде, где ты написала коментарий, после решетки должен стоять пробел, а потом текст

2024-08-09 07:51 UTC, eugene-okulik requested changes
Разберись с оставшимися ошибками, которые обнаружил Lint - там уже совсем чуть-чуть осталось

2025-01-03 14:31 UTC, ShakhistaKh commented
Не понимаю что не так(

2025-01-04 08:45 UTC, eugene-okulik requested changes

2025-01-04 08:45 UTC, eugene-okulik commented on homework/shokhista_khashimova/homework_4/task_2 done by step.py
> +my_dict = {'tuple': (1, "q", "A", "z", "word"), 'list': ["first", "second", "third", "cat", "dog"], 'dict': {'car1': 'volvo', 'car2': 'bmw'}, 'set': {"white", "black", "yellow", 2, 6.8}}
Вот здесь он говорит

> line too long (186 > 120 characters)

Просто нужно разделить строку 12 так, чтобы она была не длиннее 120 символов

2025-01-04 08:45 UTC, eugene-okulik commented on homework/shokhista_khashimova/homework_4/task_2 done.py
> +my_dict = {'tuple': (1, "q", "A", "z", "word"), 'list': ["first", "second", "third", "cat", "dog"], 'dict': {'car1': 'volvo', 'car2': 'bmw'}, 'set': {"white", "black", "yellow", 2, 6.8}}
И здесь он говорит

> line too long (186 > 120 characters)

Тоже нужно разделить строку, чтобы она не была длиннее того, что требует PEP-8

2025-01-05 08:42 UTC, eugene-okulik approved these changes
:+1:

2025-01-05 08:43 UTC, merged